### ISSUE TITLE
Error: 'Document' object not iterateable on Docker image.

### ISSUE THREAD

**Issue by umairq** [SapienzaNLP/relik#21]
I used the following string as input to the system extracting triples using relik-ie/relik-relation-extraction-large model. It works fine in demo but in docker image it resulted in error.
String: _"PapiSlot : Situs Resmi Deposit via Pulsa / Transfer Bank IDN Slot IDN Slot Nama Game: 🎰IDN Slot🎰 Platform: 📱ANDROID📱 , 📲IOS📲 , 💻WINDOWS💻 , 🖥️OSX🖥️ , dan WEB Kategori: 🎮Game🎮 Minimal Deposit: 💰Rp 10.000💰 (FAQ) Pertanyaan Mengenai Situs Papislot : Situs Resmi IDN Slot"_

It resulted in following error.
```
[2024-10-08 08:53:21,615] [ERROR] [relik.inference.serve.backend.fastapi_be.relik_endpoint:179] [PID:1] [RANK:0] 'Document' object is not iterable
Traceback (most recent call last):
  File "/home/relik-user/.local/lib/python3.10/site-packages/relik/inference/serve/backend/fastapi_be.py", line 164, in relik_endpoint
    return await self(
  File "/home/relik-user/.local/lib/python3.10/site-packages/relik/inference/serve/backend/fastapi_be.py", line 136, in __call__
    return [o.to_dict() for o in output]
  File "/home/relik-user/.local/lib/python3.10/site-packages/relik/inference/serve/backend/fastapi_be.py", line 136, in <listcomp>
    return [o.to_dict() for o in output]
  File "/home/relik-user/.local/lib/python3.10/site-packages/relik/inference/data/objects.py", line 117, in to_dict
    "triplet": [
  File "/home/relik-user/.local/lib/python3.10/site-packages/relik/inference/data/objects.py", line 118, in <listcomp>
    [[doc.to_dict() for doc in documents] for documents in window]
  File "/home/relik-user/.local/lib/python3.10/site-packages/relik/inference/data/objects.py", line 118, in <listcomp>
    [[doc.to_dict() for doc in documents] for documents in window]
TypeError: 'Document' object is not iterable
```

**Comment by bryanlzc** [comment]
I am facing the same issue as well

**Comment by dritlopes** [comment]
Same issue when trying to use the RelikOutput function "to_dict".
